šlatam teste

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -26,20 +26,27 @@ jobs:
       run: dotnet build --no-restore --configuration Release
 
     - name: Test with Coverage
-      run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
+      id: test_step
+      continue-on-error: true 
+      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
 
     - name: Generate Coverage Summary
       uses: irongut/CodeCoverageSummary@v1.3.0
       with:
         filename: '**/coverage.cobertura.xml'
         badge: true
-        fail_below_min: false
+        fail_below_min: false 
         format: markdown
-        hide_branch_rate: false
-        hide_complexity: true
-        indicators: true
         output: both
-        thresholds: '50 80'
+
+    - name: Write Summary to Job
+      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
+      
+    - name: Check Test Status
+      if: steps.test_step.outcome == 'failure'
+      run: |
+        echo "::error::Tests failed, but I generated the coverage report for you above!"
+        exit 1 
 
     - name: Write Summary to Job
       run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
